language: elixir
elixir: 1.5.2
otp_release: 20
sudo: required

scripts:
  - docker

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libtag1-dev build-essential

  - sudo apt-get install -qq gcc-6 g++-6

  - gcc --version

  - docker pull redis
  - docker run --name redis -d -p 6379:6379 redis:latest

  - mix deps.get

script:
  - mix test
  - mix credo -a

