language: elixir
elixir: 1.5.2
otp_release: 18.3
sudo: required

scripts:
  - docker

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libtag1-dev build-essential

  - add-apt-repository ppa:jonathonf/gcc-7.1
  - apt-get update
  - apt-get install gcc-7 g++-7

  - gcc --version

  - docker pull redis
  - docker run --name redis -d -p 6379:6379 redis:latest

  - mix deps.get

script:
  - mix test
  - mix credo -a

