language: elixir
elixir: 1.5.2
otp_release: 18.3
compiler: clang
sudo: required

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libtag1-dev build-essential
  - mix deps.get

script:
  - mix test
  - mix credo -a

