version: 2
jobs:
  build:
    docker:
      # - image: elixir:1.5.2
      - image: gcc:7.2.0

    working_direcotry: ~/repo

    steps:
      - checkout

      - run: apt-get update
      - run: apt-get install -y erlang libtag1-dev curl
      - run: curl -sSL https://raw.githubusercontent.com/taylor/kiex/master/install | bash -s
      - run: source "/root/.kiex/scripts/kiex"
      - run: kiex install 1.5.2
      - run: source "/root/.kiex/scripts/kiex/elixirs/elixir-1.5.2.env"

      - run: mix local.hex --force
      - run: mix local.rebar
      - run: mix deps.get
      - run: mix deps.compile
      - run: mix tes
