version: 2
jobs:
  build:
    docker:
      - image: elixir:1.5.2

    working_direcotry: ~/repo

    steps:
      - checkout

      - run: mix local.hex --force
      - run: mix local.rebar
      - run: mix deps.get
      - run: mix deps.compile
      - run: mix tes
